# This is a basic GitHub Actions workflow to run tests for your Python project.

name: Python CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main/master branches
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This job is called "build-and-test"
  build-and-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # This job will run on a matrix of Python versions
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Step 1: Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository
        uses: actions/checkout@v4

      # Step 2: Sets up the specified version of Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Run the tests
      # This command is run from the root of the repository.
      - name: Run tests
        run: |
          python -m unittest discover

